name: Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - run: zig build test --summary all
  
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      
      - name: Check examples
        run: |
         ROOT_DIR=$(pwd)
          for example in {hello,hello_app,blog,todos_orm_sqlite}; do
              EXAMPLE_DIR="$ROOT_DIR/examples/$example/"
              echo "Testing $EXAMPLE_DIR"
              cd "$EXAMPLE_DIR"

              zig build
              zig build run &
              until nc -z localhost 8080; do
                  echo "Waiting for server..."
                  sleep 1
              done

              URL="http://127.0.0.1:8080"
              if [[ "$example" == "todos_orm_sqlite" ]]; then
                  URL="http://127.0.0.1:8080/todo"
              fi
              echo "GET $URL"
              HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL || echo "failed")

              echo "Killing process for $example..."
              kill `ps -ef| grep -i $example | grep -v grep | awk '{print $2}'`
              sleep 3

              # Check the result
              if [[ "$HTTP_STATUS" == "200" ]]; then
                  echo "$EXAMPLE_DIR: OK"
              else
                  echo "$EXAMPLE_DIR: Failed with status $HTTP_STATUS"
                  exit 1
              fi
          done
